### ISSUE TITLE
reservesys task url is invalid

### ISSUE THREAD

**Issue by wizardofoz123** [beaker-project/restraint#11]
The <fetch /> elements in https://restraint.readthedocs.io/en/latest/using.html have an url that doesn't seem to work:

$ git clone git://fedorapeople.org/home/fedora/bpeck/public_git/tests.git#distribution/reservesys
Cloning into 'reservesys'...
fatal: remote error: access denied or repository not exported: /home/fedora/bpeck/public_git/tests.git#distribution/reservesys

My jobs using this url have started aborting recently. What is going on? Is the link broken? And is the reservesys task in beaker-core-tasks equivalent? It doesn't seem to work for me.

**Comment by StykMartin** [comment]
> The elements in https://restraint.readthedocs.io/en/latest/using.html have an url that doesn't seem to work:
> 
> $ git clone git://fedorapeople.org/home/fedora/bpeck/public_git/tests.git#distribution/reservesys
> Cloning into 'reservesys'...
> fatal: remote error: access denied or repository not exported: /home/fedora/bpeck/public_git/tests.git#distribution/reservesys

This is definitely obsolete and should be replaced with our reservesys (provided by Beaker)
> 
> My jobs using this url have started aborting recently. What is going on? Is the link broken? And is the reservesys task in beaker-core-tasks equivalent? It doesn't seem to work for me.

reservesys used by beaker-core-tasks should be working just fine. Can you please share the error?

**Comment by wizardofoz123** [comment]
Thank you, @StykMartin . As we discussed on IRC, the issue is with the restraint client version.
Updating everything to restraint-client-0.2.0-1 fixed the issue.

I've opened https://github.com/beaker-project/restraint/pull/14 to adjust the invalid url.
