### ISSUE TITLE
Migration from 0.1.45 to 0.2.0 is nightmare

### ISSUE THREAD

**Issue by StykMartin** [beaker-project/restraint#12]
Docs / Release notes wasn't sufficient for 0.2.0 (maybe it would be better to even bump restraint to 1.0.0 due to changes).

Well. We have to learn from mistakes.
So following this has to be addressed.
- Outline fully the scope of the changes for libssh removal in the changelog. We basically destroyed API and backward compatibility. 0.1.45 can't speak with 0.2.0. Port can't be used anymore.
- Revisit all parts of docs and update it accordingly
- Check [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1821342)

**Comment by StykMartin** [comment]
Also, one thing to consider that @danrodrig already outlined. Adding support for `port` back.

**Comment by StykMartin** [comment]
This is also connected with #11. You can't use 0.1.45 as client

**Comment by cbouchar** [comment]
I had pursued trying to keep the port when I worked on Bill's changes.  Perhaps @danrodrig fresh set of eyes may see a way to that.

**Comment by cbouchar** [comment]
In the meantime, I will work on changelog.

**Comment by StykMartin** [comment]
Closing this one. We addressed all known problems.
