### ISSUE TITLE
No 'harness.log' if External Watchdog triggered

### ISSUE THREAD

**Issue by JohnVillalovos** [beaker-project/restraint#153]
If a job runs and the External Watchdog is triggered there is no 'harness.log'

Which makes it difficult to debug the issue for why the external watchdog was triggered 😟

**Comment by danrodrig** [comment]
This is related to log manager too and it will be addressed in #152 

Thanks for reporting, @JohnVillalovos

**Comment by StykMartin** [comment]
I believe that any implementation of #152 will fix this issue as @danrodrig mentioned above.
Closing this one
