### ISSUE TITLE
restraint won't update Beaker watchdog in fetch mode from Makefile

### ISSUE THREAD

**Issue by AloisMahdal** [beaker-project/restraint#184]
I have a task with the "old school" RHTS Makefile with `TestTime` set to 12h.  I need to be able to run it with `<fetch/>` mode but also with `<rpm/>` mode.

When I run it in `<rpm/>` mode, as expected, task can run for 12h.

But in `<fetch/>` mode, the task will expire with `External Watchdog Expired` after 30 minutes.  Initially I suspected that restraint merely ignores the Makefile but from harness.log it looks like it does set its own watchdog accordingly:

    [..]
    ** Running task: 121895074 [jats://redhat.com/oamg/morft//pivot/leapp@s=0]
    *** Current Time: Sat Feb 13 15:50:45 2021  Localwatchdog at: Sun Feb 14 03:49:45 2021
    *** Current Time: Sat Feb 13 15:51:45 2021  Localwatchdog at: Sun Feb 14 03:49:45 2021
    *** Current Time: Sat Feb 13 15:52:45 2021  Localwatchdog at: Sun Feb 14 03:49:45 2021
    [..]

Calling *rstrnt-adjust-watchdog* from runtest.sh does work to adjust both.

This was observed using

 * *restraint-0.3.2-1.el7bkr.x86_64*
 * and *restraint-rhts-0.3.2-1.el7bkr.x86_64*

from Red Hat internal infrastructure.

**Comment by AloisMahdal** [comment]
> Calling rstrnt-adjust-watchdog from runtest.sh does work to adjust both.

Looking at the recipes I have, I'm probably wrong about this statement.  We've been using this command in `<rpm/>` mode successfuly for many months, but I can't say what made me think that it worked in `<fetch/>` mode.

**Comment by AloisMahdal** [comment]
OK, so the situation is a bit more weird.  I've been able to watch it in progress.

First, restraint actually does set the external watchdog to 12.5h, as seen here:


    ** Fetching task: 121908660 [/mnt/tests/REDACTED/tests/distribution/jats/run]
    ** Extracting git://REDACTED/tests/distribution#jats/run/mnt/tests/REDACTED/tests/distribution/jats/run
    ** Extracting Makefile
    ** Extracting PURPOSE
    ** Extracting README.md
    ** Extracting bkrh
    ** Extracting runtest.sh
    ** Fetch Summary: Match 5, Nonmatch 0
    ** Preparing metadata
    use_pty:FALSE make testinfo.desc
    rhts-lint testinfo.desc
    ** Refreshing peer role hostnames: Retries 0
    ** Updating env vars
    ** Updating external watchdog: 45000 seconds
    ** Installing dependencies
        [..]
        [..]
        [..]
    shellfu-bash-jats-0.0.7-1.el7.noarch
    shellfu-bash-bkrh-0.0.2-1.el7.noarch
    jattool-0.3.2-1.el7.noarch
    ** Running task: 121908660 [jats://redhat.com/oamg/morft//init]
    *** Current Time: Mon Feb 15 02:14:21 2021  User Adjusted Localwatchdog at: Mon Feb 15 14:13:24 2021
    *** Current Time: Mon Feb 15 02:15:21 2021  Localwatchdog at: Mon Feb 15 14:13:24 2021
    *** Current Time: Mon Feb 15 02:16:21 2021  Localwatchdog at: Mon Feb 15 14:13:24 2021
    use_pty:FALSE /usr/share/restraint/plugins/run_task_plugins /usr/share/restraint/plugins/run_plugins
    Skipping Multihost sync .. SERVERS/CLIENTS roles not set
    ** Completed Task : 121908660

I believe the second setting is by our runtest.sh calling `rstrnt-adjust-watchdog 12h`.

As I kept refreshing the WUI I saw it set to 12:30.

**But** after few seconds it got reverted back to :30!

Only one thing I can think of: we set the watchdog, then run our JATS tool, but that will update task to set the version field.

Here is a debug log from our runtest.sh:

        [..]
        [..]
    debug:__bkrh__curl(): cmd='([0]="curl" [1]="-vfsSL" [2]="-H" [3]="Content-Range: bytes 0-6144/6145" [4]="-H" [5]="Content-Length: 6145" [6]="-T" [7]="/tmp/tmp.4Zlve4XENe" [8]="http://lab-02.rhts.eng.brq.redhat.com:8000//recipes/9560679/tasks/121908660/logs/jats_run.env")'
    debug:jatsrun(): suite_id="jats://redhat.com/oamg/morft//"
    debug:jatsrun(): suite_dir="/usr/share/jats/suite/morft"
    debug:jatsrun(): suite_version="0.7.1"
    debug:update_duration(): dir="/usr/share/jats/suite/morft/init"
    debug:update_duration(): duration=""
    no duration specified; setting to: 12h
    debug:__bkrh__curl(): cmd='([0]="curl" [1]="-vfsSL" [2]="-d" [3]="seconds=43200" [4]="http://lab-02.rhts.eng.brq.redhat.com:8000//recipes/9560679/watchdog")'
    debug:bkrh__status(): cmd='([0]="__bkrh__taskinfo" [1]="status=Running" [2]="name=jats://redhat.com/oamg/morft//init" [3]="version=0.7.1")'
    debug:__bkrh__curl(): cmd='([0]="curl" [1]="-vfsSL" [2]="-X" [3]="PATCH" [4]="-d" [5]="status=Running" [6]="-d" [7]="name=jats://redhat.com/oamg/morft//init" [8]="-d" [9]="version=0.7.1" [10]="http://lab-02.rhts.eng.brq.redhat.com:8000//recipes/9560679/tasks/121908660/")'
    debug:saturnin__main():starting jattool v0.3.2 bash v4.2.46(2)-release
    debug:saturnin__main():*=runtest jats://redhat.com/oamg/morft//init
    debug:_saturnin__runsc():binpath="/usr/libexec/jattool/jattool-runtest"
    debug:_saturnin__runsc():$*='jats://redhat.com/oamg/morft//init'
    debug:_saturnin__isen_builtin():enbltns=":conf:"
    debug:_saturnin__runsc():isenbin="T"
    debug:_saturnin__runsc():isenblt="F"
        [..]
        [..]

See

 1. we upload some early log.
 2. then we update watchdog (again, I added this believing that rstrnt-adjust-watchdog did nothing).
 3. then we update task data to be more precise.

Could the third curl call undo the current watchdog setting?

**Comment by AloisMahdal** [comment]
>  1. we upload some early log.
>  2. then we update watchdog (again, I added this believing that rstrnt-adjust-watchdog did nothing).
>  3. then we update task data to be more precise.
>
> Could the third curl call undo the current watchdog setting?

Looks like it could:  I changed the order to:

 1. we upload some early log.
 3. then we update task data to be more precise.
 2. then we update watchdog.

and the last watchdog value sticks.

At any rate, the issue is apparently not a bug restraint.  Closing.

**Comment by StykMartin** [comment]
Well done @AloisMahdal.
