### ISSUE TITLE
restraint in standalone mode doesn't print task being run

### ISSUE THREAD

**Issue by wizardofoz123** [beaker-project/restraint#187]
When restraint is invoked in standalone mode with a Beaker host (e.g. `restraint --job /tmp/tmp_oevcnpg/job.xml --host 1234=root@hostname.com `), the name of the task that is actually running isn't printed to system console.log, only "reservesys" that is keeping the Beaker host up.

```
[   83.210387] restraintd[6991]: * Fetching recipe: http://lab-02.rhts.eng.bos.redhat.com:8000//recipes/9621684/ 
[   83.322050] restraintd[6991]: * Parsing recipe                               
[   83.322464] restraintd[6991]: * Running recipe                               
[   83.322632] restraintd[6991]: ** Continuing task: 122481538 [/mnt/tests/github.com/beaker-project/beaker-core-tasks/archive/master.tar.gz/reservesys] 
[   83.324688] restraintd[6991]: ** Preparing metadata                          
[   83.464927] restraintd[6991]: ** Refreshing peer role hostnames: Retries 0   
[   83.580528] restraintd[6991]: ** Updating env vars                           
[   83.580772] restraintd[6991]: *** Current Time: Thu Feb 25 17:00:05 2021  Localwatchdog at:  * Disabled! * 
[   83.587069] restraintd[6991]: ** Running task: 122481538 [/distribution/reservesys] 
[  269.758887] LTP: starting kmsg01             
```

**Comment by StykMartin** [comment]
I'm going to take my crystal ball and guess what is in job.xml.

I can see "Continuing task" instead of "Fetching task". What happened there before? Did you reboot the box?

**Comment by wizardofoz123** [comment]
@StykMartin AFAIK, none of that is relevant to the issue. No, I haven't rebooted the box, but the tests may have. It shouldn't be important.

You should be able to reproduce anytime by:

-  reserving a Beaker machine 
-  using restraint in standalone mode to run tasks on it

**Comment by StykMartin** [comment]
> @StykMartin AFAIK, none of that is relevant to the issue. No, I haven't rebooted the box, but the tests may have. It shouldn't be important.

Well, I asked because I wanted to know if there is even a problem with restraint reporting directly to Beaker.
Furthermore, you running standalone Restraint that will spawn a new Restraintd in the box.
AFAIK all payload should be in your Restraint, not console.

> 
> You should be able to reproduce anytime by:
> 
>     * reserving a Beaker machine
> 
>     * using restraint in standalone mode to run tasks on it

**Comment by StykMartin** [comment]
+ At this point I would say the whole thing about Restraintd reporting to console is completely useless.
It is Restraintd running reservesys, where is a way how to run Beaker machine without this blocking restraintd. The output of this is a separate topic.

So things that truly matters here.
restraintd (restraint) version rpm
restraint cli (restraint-client) version rpm

And if we are missing payload in client received from running restraintd.

**Comment by wizardofoz123** [comment]
I'm getting some unexpected behavior, sometimes everything is in restraint, sometimes the output about what task is running is in console. Sorry, I'll need to run reproducers for a while.

**Comment by wizardofoz123** [comment]
@StykMartin Right, after some testing with very lightweight config, the console output goes to console.log in Beaker and portion is also captured in dmesg.log.

To carefully move this further, my question is: is this the intended behavior? Also, can I change this and make sure all console.log content is in restraint output directory (e.g. job.01 for job.xml )?

RPM versions are:

server: restraint-0.3.2-1.el8bkr.aarch64
client: restraint-client: restraint-client-0.3.2-1.el8bkr.x86_64

**Comment by StykMartin** [comment]
@wizardofoz123 What exactly do you need, when you running client <--> server Restraint?
If you execute restraint-client in verbose, you can get information about execution.

```
[192.168.42.101      ] ** Fetching task: 1 [/mnt/tests/github.com/beaker-project/beaker-core-tasks/archive/master.tar.gz/command]
[192.168.42.101      ] ** Extracting command/
[192.168.42.101      ] ** Extracting command/Makefile
[192.168.42.101      ] ** Extracting command/PURPOSE
[192.168.42.101      ] ** Extracting command/runtest.sh
[192.168.42.101      ] ** Fetch Summary: Match 4, Nonmatch 149
[192.168.42.101      ] ** Preparing metadata
[192.168.42.101      ] use_pty:FALSE make testinfo.desc
[192.168.42.101      ] ** Updating env vars
[192.168.42.101      ] ** Updating external watchdog: 12600 seconds
[192.168.42.101      ] ** Installing dependencies
[192.168.42.101      ] ** Running task: 1 [/distribution/command]
```

If you will need more, or you looking for specific information, then we can create RFE for this functionality.

**Comment by wizardofoz123** [comment]
@StykMartin After some specific checking, I can rephrase my question. Is restraint expected to capture anything written to `/dev/kmsg`?
As far as I can see, anything written to `/dev/kmsg` ends up in Beaker `console.log` and isn't captured in restraint output files.

**Comment by StykMartin** [comment]
> @StykMartin After some specific checking, I can rephrase my question. Is restraint expected to capture anything written to `/dev/kmsg`?

No. It is not expected that Restraint will gather the output.

> As far as I can see, anything written to `/dev/kmsg` ends up in Beaker `console.log` and isn't captured in restraint output files.

Beaker is capable to capture this because we have access to serial consoles. In Red hat this is managed by conserver where Beaker just reading files

**Comment by wizardofoz123** [comment]
Then 

> > @StykMartin After some specific checking, I can rephrase my question. Is restraint expected to capture anything written to `/dev/kmsg`?
> 
> No. It is not expected that Restraint will gather the output.
> 

Then this isn't a restraint issue.

Closing the issue. I will reopen, if I'm certain that I see output that is supposed to be captured by restraint and isn't.

Thank you.
