### ISSUE TITLE
20_unconfined doesn't work on recent Fedora (>=34)

### ISSUE THREAD

**Issue by bgoncalv** [beaker-project/restraint#189]
/usr/share/restraint/plugins/task_run.d/20_unconfined contains:

    local the_rpms="$(rpm -q --whatprovides redhat-release)"

But new fedora releases don't provide `redhat-release`

This was done as part of https://src.fedoraproject.org/rpms/fedora-release/c/00420683b40721ad6efa8391af71a077e8c7773f?branch=rawhide

This causes the following messages to be shown:

    /usr/share/restraint/plugins/task_run.d/20_unconfined: eval: line 22: conditional binary operator expected
    /usr/share/restraint/plugins/task_run.d/20_unconfined: eval: line 22: syntax error near `no'
    /usr/share/restraint/plugins/task_run.d/20_unconfined: eval: line 22: `[[ package no is not installed'
    /usr/share/restraint/plugins/task_run.d/20_unconfined: eval: line 22: conditional binary operator expected
    /usr/share/restraint/plugins/task_run.d/20_unconfined: eval: line 22: syntax error near `no'
    /usr/share/restraint/plugins/task_run.d/20_unconfined: eval: line 22: `[[ package no is not installed'
    /usr/share/restraint/plugins/task_run.d/20_unconfined: eval: line 22: conditional binary operator expected
    /usr/share/restraint/plugins/task_run.d/20_unconfined: eval: line 22: syntax error near `no'
    /usr/share/restraint/plugins/task_run.d/20_unconfined: eval: line 22: `[[ package no is not installed'

**Comment by bgoncalv** [comment]
This works:

    rpm -q --whatprovides /etc/redhat-release
    fedora-release-common-34-0.9.noarch

**Comment by StykMartin** [comment]
This is already fixed in master. PR https://github.com/beaker-project/restraint/pull/180
