### ISSUE TITLE
Restraint Rawhide(f35) does not compile due to SIGSTKSZ error 

### ISSUE THREAD

**Issue by cbouchar** [beaker-project/restraint#201]
Seeing a compile error with thirdparty package m4 due to change in glibc's SIGSTKSZ #define.
Previously it was a STATIC integer which could be handled during 'C' preprocessing but now
it is defined with sysconf() so value is only available during runtime.    The ^~~~~~ below actually sits
beneath SIGSTKSZ.

/usr/include/signal.h:315,
                 from ./signal.h:52,
                 from c-stack.c:49:
c-stack.c:55:26: error: missing binary operator before token "("
   55 | #elif HAVE_LIBSIGSEGV && SIGSTKSZ < 16384
      |                          ^~~~~~~~

**Comment by StykMartin** [comment]
This is closed by #202 .
