### ISSUE TITLE
[rfe] Client option/way to specify ssh port

### ISSUE THREAD

**Issue by lukaszachy** [beaker-project/restraint#208]
Hi, Could you please (re)introduce option to specify which ssh port restraint client connects to?
(used to be `--host=1=root@127.0.0.1/10037`)

In [tmt](https://github.com/psss/tmt) we are using testcloud in user qemu session and individual VMs are available via localhost but ssh listens on different ports - so in order to connect to that VM I need restraint client to use port I specify.

**Comment by StykMartin** [comment]
https://github.com/beaker-project/restraint/blob/7d3d858ac68d8370b7d0c87980562f4d1c37f3d8/src/client.c#L1839
https://github.com/beaker-project/restraint/blob/7d3d858ac68d8370b7d0c87980562f4d1c37f3d8/src/client.c#L1040

Isn't this what you looking for @lukaszachy

**Comment by StykMartin** [comment]
It is even possible to define the whole rsh
https://github.com/beaker-project/restraint/blob/7d3d858ac68d8370b7d0c87980562f4d1c37f3d8/src/client.c#L1844

**Comment by lukaszachy** [comment]
Unfortunately it doesn't seems so - it t:
```
$ restraint --job job.xml --host=1=root@127.0.0.1 --port 10038
Using ./job.02 for job run
No result
Connecting to host: root@127.0.0.1, recipe id:1
[127.0.0.1           ] use_pty:FALSE ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=5 root@127.0.0.1 -- restraintd --port 10038 --stdin
[127.0.0.1           ] ssh: connect to host 127.0.0.1 port 22: Connection refused
One or more tasks failed [restraint-error-quark, 10]
```
I had disabled sshd on localhost, when I enabled it it still tries to run restraintd on my laptop, not the VM.
```
$ restraint --job job.xml --host=1=lzachar@127.0.0.1 --port 10038
Using ./job.05 for job run
No result
Connecting to host: lzachar@127.0.0.1, recipe id:1
[127.0.0.1           ] use_pty:FALSE ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=5 me@127.0.0.1 -- restraintd --port 10038 --stdin
me@127.0.0.1's password: 
[127.0.0.1           ] bash: restraintd: command not found
One or more tasks failed [restraint-error-quark, 10]
```

**Comment by StykMartin** [comment]
Oh right @lukaszachy, I messed up. Port is passed to restraintd on the opposite side.
However, this should be possible to perform w/ rsh. Let me try to do some tricks.

**Comment by StykMartin** [comment]
I changed my `sshd` to listen on 10420.
```
sudo grep Port /etc/ssh/sshd_config
Port 10420
```

Then I tried to connect to it via following command
```
restraint -j re.xml -t root@192.168.42.101 -v -e "ssh -p 10420"
```

And everything worked as expected
```
Connecting to host: root@192.168.42.101, recipe id:1
[192.168.42.101      ] use_pty:FALSE ssh -p 10420 root@192.168.42.101 -- restraintd --port 0 --stdin
[192.168.42.101      ] Listening on http://localhost:45509
```

**Comment by lukaszachy** [comment]
wow. Indeed. Thank you @StykMartin.
Could it be documented ? I read about -e in --help however didn't realise that command  can contains arguments as well.

**Comment by StykMartin** [comment]
Sure, I will update documentation regarding this. Thank you for pointing out the issue.
