### ISSUE TITLE
Missing Fedora34 repo

### ISSUE THREAD

**Issue by lukaszachy** [beaker-project/restraint#212]
Hi, Installation instructions says to use `https://beaker-project.org/yum/beaker-harness-Fedora.repo`
however currently there are no repodata for for freshly released **Fedora34**.

**Comment by StykMartin** [comment]
Hello there.

RH is definitely not using the upstream resources for the harness. I allocated some space in the AOE cluster for this purpose, therefore change here will not affect you.

However, yeah, we need to build Restraint for F34. Infra is missing in upstream at this moment. 

So... @renanrodrigo can you build it for RH and manually sync it for us, peasants, upstream? As a reward, I will pass you some 🍻 .

**Comment by renanrodrigo** [comment]
@StykMartin we have it built, it's a matter of uploading.
So yes, can do :)

Beer is the best trading coin we will ever have around :D

**Comment by renanrodrigo** [comment]
Sorry for the delay :|

[It's there](https://beaker-project.org/yum/harness/Fedora34/)
