### ISSUE TITLE
Add OOMPolicy=continue to restraintd service

### ISSUE THREAD

**Issue by bgoncalv** [beaker-project/restraint#224]
systemd supports this policy: https://www.freedesktop.org/software/systemd/man/systemd.service.html#OOMPolicy=

It would be nice if restraintd to continues to run even if a test trigger OOM, so it doesn't affect the test execution.

In same cases the OOM can even be intentional, like `LTP/OOM` test case.

**Comment by bgoncalv** [comment]
@cbouchar do you maintain the restraint packages for the beaker harness?

**Comment by cbouchar** [comment]
I am one of the maintainers.

**Comment by bgoncalv** [comment]
> I am one of the maintainers. I'm tied up with other restraint commitments at the moment.

That's fine, it is not urgent, but would be nice to have this set in the package.
