### ISSUE TITLE
Allow to specify restraintd port

### ISSUE THREAD

**Issue by danrodrig** [beaker-project/restraint#28]
In Restraint 0.1.45 and older the "-p, --port" option let users choose the port where restraintd listened to HTTP requests. If the option was not used, the port was set to 8081 as default.

In Restraint 0.2.0 the option is removed and the port is chosen randomly on every run. There is no way of defining the port, and when restraintd is running as service, the system needs to be inspected to find out the port being used.

In some scenarios it's expected that the port is the same for different runs. See https://bugzilla.redhat.com/show_bug.cgi?id=1823545

A simply fix to the "/distribution/reservesys" case is to recover the -p, --option, and set a default port for the restratind service. This should entail,

0. Recover "-p, --port" option in server and client. If the option is not used, keep the dynamic port behavior.
1. In init script and systemd unit, set a default value for the port using the --port option.

This is simpler than changing beaker-core-tasks without breaking older Restraint versions.

It's not in scope to recover the HTTP endpoints to control a job, "/run" and "/continue".

Relates to #12.

**Comment by danrodrig** [comment]
@StykMartin @cbouchar can you take a look, please?

**Comment by StykMartin** [comment]
0. I'm completely fine with adding `-p, --port` back if it is feasible.
1. This has to be documented properly.

**Comment by cbouchar** [comment]
I had pursued this when working on sshlib removal and at that time could not find a solution to make that happen.  Perhaps a fresh set of eyes can find a solution.  I can pick-up the reservesystem issue if it is an issue.

**Comment by danrodrig** [comment]
@StykMartin,

> 0. I'm completely fine with adding `-p, --port` back if it is feasible.

Easy.

> 1. This has to be documented properly.

Yes.

@cbouchar,

> I can pick-up the reservesystem issue if it is an issue.

You don't need to, it's covered here.

**Comment by StykMartin** [comment]
Great! Thanks for your effort @danrodrig

**Comment by cbouchar** [comment]
Daniel it sounds like you have this covered then. TY
