### ISSUE TITLE
Restraint failed to run w/ fetch from git

### ISSUE THREAD

**Issue by StykMartin** [beaker-project/restraint#41]
Restraint failed on the following:
```
/usr/share/restraint/plugins/task_run.d/10_bash_login: line 7: 91696 Terminated              setsid "$@"
```
Task is automatically reported as failure.
Execution can be found in `J:4206965`

**Comment by StykMartin** [comment]
Hi Carol (@cbouchar), can you take a look into this one.

At this point it is not confirmed that this is an issue in Restraint. Maybe users are running something wrong or hitting some corner case.

**Comment by cbouchar** [comment]
Yes

**Comment by cbouchar** [comment]
This is not a restraint issue.  The task contains "trap 'trap - SIGTERM && kill -- -$$' SIGINT SIGTERM EXIT" which was causing it to kill itself so 10_bash_login does not run to completion.  I ran the code manually by doing the following:
cd /mnt/tests/gitlab.cee.redhat.com/kernel-performance/sched/scheduler-benchmarks/-/archive/master/scheduler-benchmarks-master.tar.gz/MasterTask
export MASTER_PARAM="--benchmark Pig-test"
export TEST_PARAM="--no_rsync --iterations 1 --minimum_threads 4 --maximum_threads 4"
export RSTRNT_LOGGING=4
/usr/share/restraint/plugins/run_task_plugins ./runtask.sh

**Comment by jirka-h** [comment]
Thanks a lot for the update! 

I have tried to disable traps before the end of the script with 
trap - EXIT SIGINT SIGTERM SIGHUP
I will need to check why it's not working. 

I have now disabled traps all together and I have restarted the jobs to verify that it fixes the problem. 

Background info: we start lots of monitoring processes in the background. The traps are there to make sure that all child processes are properly stopped when the main script is killed.

**Comment by cbouchar** [comment]
The task is now running successfully. ref J4211675

**Comment by jirka-h** [comment]
I was disabling the trap in the wrong script - it has to be disabled in the MasterTask script. 

@cbouchar - you did an AMAZING job to debug this issue. It has required to deep dive into the structure of our tests and it wasn't easy. Thank you for going the extra mile! I do appreciate that!

**Comment by jirka-h** [comment]
Final remark - I have redesigned trap code and now everything works just fine, even with the trap being active. Putting it here for the reference:

```
trap_with_arg() { # from https://stackoverflow.com/a/2183063/804678
  local func="$1"; shift
  for sig in "$@"; do
    trap "$func $sig" "$sig"
  done
}

stop() {
  trap - SIGINT EXIT
  printf '\n%s\n' "received $1, killing children"
  kill -s SIGINT -- -$BASHPID
}

trap_with_arg 'stop' EXIT SIGINT SIGTERM SIGHUP
```

**Comment by StykMartin** [comment]
Thanks, @cbouchar. Great job!
