### ISSUE TITLE
Remove dep to /usr/bin/pgrep

### ISSUE THREAD

**Issue by StykMartin** [beaker-project/restraint#44]
During `0.2.1` development we added requirement to have `/usr/bin/pgrep` in the system.
This is the only package that we don't have as static for `restraint rpm` at this moment.

It would be great if we can get rid of it and replace it with something that we don't need to bring deps. This will increase portability.

So the question is. Are we fine with adding runtime dep to base restraint?

**Comment by StykMartin** [comment]
@beaker-project/restraint-maintainers

**Comment by danrodrig** [comment]
> Are we fine with adding runtime dep to base restraint?

I'd say that we should avoid adding runtime deps. For Restraint, the "cleaner" we keep the system, the better.

**Comment by cbouchar** [comment]
How does one acquire process IDs for restraintd via 'C' code?  I believe 'pidof' was also an issue.  I will keep googling.

**Comment by cbouchar** [comment]
The pidof/pgrep came into being for rstrnt-cmds.  We could require user always provide restraintd pid and not look it up for them.  In that case, we would remove -c and just have --pid/i as argument.

**Comment by StykMartin** [comment]
https://github.com/beaker-project/restraint/pull/36 should be obsolete w/ correct patching
