### ISSUE TITLE
Error field must be initialized

### ISSUE THREAD

**Issue by cbouchar** [beaker-project/restraint#48]
I noticed code was merged where the error field was not initialized to NULL.
This was an omission of a review comment in Issue #42.  Without this change,
code will behave unpredictably.

**Comment by danrodrig** [comment]
https://github.com/beaker-project/restraint/blob/c05e7d02abae8b6db40a648408dcc24b2e3df173/src/server.c#L603

**Comment by cbouchar** [comment]
Never seen initialization coded that way it but it will work.
