### ISSUE TITLE
Evaluate ansible/OS limitation issues

### ISSUE THREAD

**Issue by cbouchar** [beaker-project/restraint#56]
What are the limitation issues as ansible progresses through OSs (RHEL, Fedora)? Can we even run ansible on RHEL 5?  What Python versions are required and is it in conflict with restraint?

**Comment by danrodrig** [comment]
Regarding using Ansible to manage RHEL 5 nodes: https://www.ansible.com/blog/using-ansible-to-manage-rhel-5-yesterday-today-and-tomorrow

**Comment by cbouchar** [comment]
We all met and discussed the content of the article and reality of the real world.  According to the article, support for RHEL 5 is going away in 2020.  Martin said even if not supported, if a customer in dire need for a change, changes still could be made so this does not release RHEL5 for us.   The article suggests to use a newer version of python and this installed version doesn't need to be the default version as ansible allows configuration to allow for use of alternate python library.  Martin said in his experience this combination doesn't work.  The plan is to use whatever default exists for each distro.  The Version support between RHEL OSs, python, and ansible is as follows:

RHEL 5 - python 2.4    Ansible 2.3
RHEL 6 - python 2.6    Ansible 2.4
RHEL 7 - python 2.7    Ansible 2.7
RHEL 8 - python 3.3    Ansible 2.7

Something to keep in mind, while going through ansible training class for version 2.7a lot of behavior differences were introduced in Ansible version 2.4/2.5.
Here are some notes I jotted down with respect to differences I capturedfrom the class: 
* Vault password changes. 
Ansible earlier than vs 2.4
     Ansible-playbook –ask-vault-pass site.yml 
otherwise
     Ansible-playbook –vault-id @prompt site.yml 
* Starting with vs ansible 2.4 you can use multiple vault passwords 
* Ansible Facts setup seem to be done differently.  Wondering if between different
   versions whether data retrieve could be different. 
* The Facts variable names pre and post ansible 2.5 were different.  Pre 2.5 all
     vars were prefixed with ansible_.  This can be changed by
     setting inject_facts_as_vars to false in [default] section of ansible config file.
 * File module has difference in behavior. Ref: state
 * Looping done differently before and after ansible 2.5
 * Ansible-inventory command available since 2.4
 * In ansible 2.4, 'include' replaced with include_tasks, import_tasks, & import_playbook. Still supported (for how long though?) but best to use latest.
 * RHEL System Roles available since RHEL 7.4 or RHEL 6.1
