### ISSUE TITLE
Upgrade third-party GLib to latest released version

### ISSUE THREAD

**Issue by StykMartin** [beaker-project/restraint#9]
Restraint is using `GLib 2.56.4` in static builds. However, the latest released version of `GLib` right now is `2.64.x`. We should align with this version as we are gathering more problems with the old `GLib` version.
For example #7 and this is only the tip of iceberg.

Possible problems:
- Autotools is no longer used / [Meson](https://mesonbuild.com/) is used instead
- Backward compatibility. CentOS 5 is still supported

**Comment by ernestask** [comment]
Good luck.
